<a href="https://colab.research.google.com/github/AaritShrama/Telco-Customer-Churn-Using-PyTorch/blob/main/Telco_Customer_Churn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# STEP-1 : IMPORT REQUIRED LIBRARIES

import pandas as pd
import matplotlib.pyplot  as plt
from sklearn.model_selection import train_test_split
import torch.nn as nn
import torch.optim as optim
import torch
from torch.utils.data import Dataset , DataLoader
from sklearn.preprocessing import StandardScaler

In [ ]:
# STEP-2 : IMPORT DATAFRAME

df = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [ ]:
# STEP-3 : DROP ID COLUMN (IRRELEVANT TO THE NN)

df.drop('customerID' , axis = 1, inplace = True)
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [ ]:
df.dtypes

gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [ ]:
# STEP-4 : FIX THE DATA IN THE TABLE TO MAKE IT APPROPRIATE FOR A NN

df['Churn']= df['Churn'].map({'Yes': 1, 'No': 0})

columns = ['gender', 'Partner', 'Dependents', 'PhoneService',
           'PaperlessBilling']
for column in columns:
  df[column] = df[column].map({'Yes': 1, 'No': 0,
                               'Male': 1, 'Female': 0})
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,1,0,1,0,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,1,Electronic check,29.85,29.85,0
1,1,0,0,0,34,1,No,DSL,Yes,No,Yes,No,No,No,One year,0,Mailed check,56.95,1889.5,0
2,1,0,0,0,2,1,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,1,Mailed check,53.85,108.15,1
3,1,0,0,0,45,0,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,0,Bank transfer (automatic),42.30,1840.75,0
4,0,0,0,0,2,1,No,Fiber optic,No,No,No,No,No,No,Month-to-month,1,Electronic check,70.70,151.65,1

In [ ]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")
df["TotalCharges"].fillna(df["TotalCharges"].median(), inplace=True)

y = df["Churn"]
X = df.drop("Churn", axis=1)

X = pd.get_dummies(X, drop_first=True)
X = X.astype(int)

/tmp/ipython-input-3143848126.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["TotalCharges"].fillna(df["TotalCharges"].median(), inplace=True)

In [ ]:
X.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,MultipleLines_No phone service,...,TechSupport_Yes,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,0,1,0,1,0,1,29,29,1,...,0,0,0,0,0,0,0,0,1,0
1,1,0,0,0,34,1,0,56,1889,0,...,0,0,0,0,0,1,0,0,0,1
2,1,0,0,0,2,1,1,53,108,0,...,0,0,0,0,0,0,0,0,0,1
3,1,0,0,0,45,0,0,42,1840,1,...,1,0,0,0,0,1,0,0,0,0
4,0,0,0,0,2,1,1,70,151,0,...,0,0,0,0,0,0,0,0,1,0

In [ ]:
y.head()

0    0
1    0
2    1
3    0
4    1
Name: Churn, dtype: int64

In [ ]:
# STEP-5 : TRAIN-TEST SPLIT

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=17)

In [ ]:
# STEP-6: SCALING & TENSOR CONVERSION OF THE DATA

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train.values)
X_test  = scaler.transform(X_test.values)

X_train = torch.tensor(X_train, dtype=torch.float32)
X_test  = torch.tensor(X_test, dtype=torch.float32)

y_train = torch.tensor(y_train.values, dtype=torch.float32)
y_test  = torch.tensor(y_test.values, dtype=torch.float32)

In [ ]:
# STEP-7 : CUSTOM DATASET CLASS FORMATION

class ChurnDataset(Dataset):
    def __init__(self, X, y):
        self.X = X
        self.y = y

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

In [ ]:
train_data = ChurnDataset(X_train, y_train)
test_data  = ChurnDataset(X_test, y_test)

train_loader = DataLoader(train_data, batch_size=32, shuffle=True)
test_loader  = DataLoader(test_data, batch_size=32, shuffle=False)

In [ ]:
# STEP-8 : NEURAL NETWORK SETUP

class ChurnNN(nn.Module):

  def __init__(self , num_features):
    super().__init__()
    self.Network = nn.Sequential(
        nn.Linear(num_features , 32),
        nn.ReLU(),
        nn.Dropout(0.3),
        nn.Linear(32 , 16),
        nn.ReLU(),
        nn.Linear(16 , 1)
    )

  def forward(self,x):
    return self.Network(x)

model = ChurnNN(X_train.shape[1])

In [ ]:
# STEP-9 : PARAMETERS

loss = nn.BCEWithLogitsLoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)
epochs = 100

In [ ]:
# STEP-10 : TRAINING LOOP

for epoch in range (epochs):

  epoch_loss = 0.0

  for batch_features,batch_labels in train_loader:

    y_pred = model.forward(batch_features).squeeze()
    batch_loss = loss(y_pred, batch_labels)

    optimizer.zero_grad()
    batch_loss.backward()
    optimizer.step()

    epoch_loss += batch_loss.item()

  avg_epoch_loss = epoch_loss / len(train_loader)
  print('epoch - ', epoch+1 , 'loss - ', avg_epoch_loss)

epoch -  1 loss -  0.4498397762660926
epoch -  2 loss -  0.42914655526815837
epoch -  3 loss -  0.42377174750896496
epoch -  4 loss -  0.42009507363798926
epoch -  5 loss -  0.41957251340319207
epoch -  6 loss -  0.41895948863972376
epoch -  7 loss -  0.41617062940435895
epoch -  8 loss -  0.4172130627820721
epoch -  9 loss -  0.4167425385807867
epoch -  10 loss -  0.40888130589056826
epoch -  11 loss -  0.40888033066428986
epoch -  12 loss -  0.4121997055865951
epoch -  13 loss -  0.41527185096579083
epoch -  14 loss -  0.4065217015433446
epoch -  15 loss -  0.4070992860416908
epoch -  16 loss -  0.409253696095472
epoch -  17 loss -  0.4139354084171144
epoch -  18 loss -  0.41059991439520305
epoch -  19 loss -  0.4086191098568803
epoch -  20 loss -  0.40707099471388564
epoch -  21 loss -  0.4066905271535539
epoch -  22 loss -  0.40228856990566364
epoch -  23 loss -  0.40341995917471113
epoch -  24 loss -  0.40520606463575093
epoch -  25 loss -  0.40151634635561606
epoch -  26 loss -  0.40283494867847464
epoch -  27 loss -  0.4076421509186427
epoch -  28 loss -  0.40733638397381133
epoch -  29 loss -  0.39964730229418155
epoch -  30 loss -  0.3977592510018645
epoch -  31 loss -  0.39587925357670434
epoch -  32 loss -  0.4015232033311984
epoch -  33 loss -  0.39841507846689495
epoch -  34 loss -  0.39612608954394607
epoch -  35 loss -  0.39393018135579966
epoch -  36 loss -  0.40012171898184523
epoch -  37 loss -  0.40409017627858845
epoch -  38 loss -  0.39498987238285904
epoch -  39 loss -  0.39304634415160467
epoch -  40 loss -  0.39550702391707965
epoch -  41 loss -  0.3912815749645233
epoch -  42 loss -  0.39662876026441823
epoch -  43 loss -  0.3934754925427464
epoch -  44 loss -  0.39227898258947386
epoch -  45 loss -  0.395137724482407
epoch -  46 loss -  0.39610537389914197
epoch -  47 loss -  0.3920644935073152
epoch -  48 loss -  0.39362788444521735
epoch -  49 loss -  0.39361406728035986
epoch -  50 loss -  0.3869809678382119
epoch -  51 loss -  0.3895946485174578
epoch -  52 loss -  0.3890105707328872
epoch -  53 loss -  0.3863335081749717
epoch -  54 loss -  0.38504458020972665
epoch -  55 loss -  0.3896751674049992
epoch -  56 loss -  0.38447039620687734
epoch -  57 loss -  0.3822782839422172
epoch -  58 loss -  0.3838449673632444
epoch -  59 loss -  0.3866680953125496
epoch -  60 loss -  0.38575231818492806
epoch -  61 loss -  0.37910363886315945
epoch -  62 loss -  0.38542317384380403
epoch -  63 loss -  0.39306928991934675
epoch -  64 loss -  0.3822405851830197
epoch -  65 loss -  0.382267234857473
epoch -  66 loss -  0.38359393667703295
epoch -  67 loss -  0.3835733341800291
epoch -  68 loss -  0.38205168821380636
epoch -  69 loss -  0.37863405831789565
epoch -  70 loss -  0.37817961785752896
epoch -  71 loss -  0.3751680807205243
epoch -  72 loss -  0.377568932323806
epoch -  73 loss -  0.3783819593783826
epoch -  74 loss -  0.3777931917690288
epoch -  75 loss -  0.38101315203696323
epoch -  76 loss -  0.3840693899635541
epoch -  77 loss -  0.38538492424676646
epoch -  78 loss -  0.3782210392130297
epoch -  79 loss -  0.3755636130180736
epoch -  80 loss -  0.3803625968048128
epoch -  81 loss -  0.3742899019165901
epoch -  82 loss -  0.37338689112730616
epoch -  83 loss -  0.37563641057849606
epoch -  84 loss -  0.3852665788036282
epoch -  85 loss -  0.37432932601136676
epoch -  86 loss -  0.3826085113536167
epoch -  87 loss -  0.371295388640657
epoch -  88 loss -  0.371873023651414
epoch -  89 loss -  0.37957160410571233
epoch -  90 loss -  0.37922411517234844
epoch -  91 loss -  0.37685742081895385
epoch -  92 loss -  0.3797856509517142
epoch -  93 loss -  0.37619654783758066
epoch -  94 loss -  0.3781691104342035
epoch -  95 loss -  0.3777908506871617
epoch -  96 loss -  0.3794183547550676
epoch -  97 loss -  0.3708280371238956
epoch -  98 loss -  0.3729578217880874
epoch -  99 loss -  0.3726723633580289
epoch -  100 loss -  0.3819974257616

In [ ]:
model.eval()

total = 0
correct = 0

with torch.no_grad():
    for batch_features, batch_labels in test_loader:

        # forward pass
        out = model(batch_features).squeeze()

        # sigmoid + threshold
        probs = torch.sigmoid(out)
        preds = (probs >= 0.5).float()

        total += batch_labels.size(0)
        correct += (preds == batch_labels).sum().item()

print("Accuracy -", correct / total)

Accuracy - 0.7821149751596878